### ISSUE TITLE
WAU install checkbox

### ISSUE THREAD

**Issue by KnifMelti** [Romanitho/Winget-Install-GUI#18]
If one install WAU, the checkbox must be unchecked after install (otherwise it runs the task again every time an app installation takes place)

**Comment by Romanitho** [comment]
by default WAU install is unchecked, no?

**Comment by KnifMelti** [comment]
Yes, but if you install WAU and then changes back to the app list and install an app it tries to install AAY again (until you untick the box)

**Comment by Romanitho** [comment]
very specific use case :) but we can try to uncheck when "Install" button is clicked.
