### ISSUE TITLE
Check if added to list...

### ISSUE THREAD

**Issue by KnifMelti** [Romanitho/Winget-Install-GUI#22]
Even if not added to the list it tries to install...

![image](https://user-images.githubusercontent.com/102996177/167694250-e550cf20-e86d-42a7-a0c9-8cc077e66100.png)

**Comment by KnifMelti** [comment]
...this happens if an application has been added to the list and the been removed...

**Comment by Romanitho** [comment]
Thanks for the info. I'll check that tomorrow

**Comment by Romanitho** [comment]
Fixed !
