### ISSUE TITLE
New Pre-release...

### ISSUE THREAD

**Issue by KnifMelti** [Romanitho/Winget-Install-GUI#23]
https://github.com/microsoft/winget-cli/releases/tag/v1.3.1251-preview

**Comment by Romanitho** [comment]
Yep ive seen that today. Not sure that it brings that much stuff for us

**Comment by Romanitho** [comment]
WiGui dev branch updated with this one

**Comment by Romanitho** [comment]
By the way, I changed the way to access Admin Tools in WiGui. Just press F10 to see it now :)

**Comment by KnifMelti** [comment]
He, the permalinks for https://docs.microsoft.com/en-AU/cpp/windows/latest-supported-vc-redist?view=msvc-170 x86/x64 are at the moment down for us :)
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Romanitho** [comment]
yes, I noticed as well. I thought I did something wrong :)
2019 works. I'll switch to it

**Comment by KnifMelti** [comment]
It works again :)

**Comment by Romanitho** [comment]
Thanks :) I'll rollback to 2022
