### ISSUE TITLE
No longer works : no software found

### ISSUE THREAD

**Issue by accnetdev** [Romanitho/Winget-Install-GUI#55]
Hi, I must inform you that GiGui 1.6.4 no longer works, no software found and WAU is installing but does not work.
What's wrong ?
Have a good day.

**Comment by accnetdev** [comment]
No application found

**Comment by accnetdev** [comment]
![20220628_183852_PREDATORW10_eproust_capture](https://user-images.githubusercontent.com/32092909/176234181-94fd1bd1-139d-4cac-95c5-a178e1bc6c68.png)

**Comment by accnetdev** [comment]
I said any search get error No application found

**Comment by Romanitho** [comment]
if you open cmd and type `winget search 7zip --accept-source-agreements --source winget` what do you have ?

**Comment by accnetdev** [comment]
winget search 7zip --accept-source-agreements --source winget
Nom               ID                     Version            Correspondance
--------------------------------------------------------------------------
7-Zip             7zip.7zip              22.00              Moniker: 7zip
7-Zip ZS          mcmilk.7zip-zstd       21.03 ZS v1.5.0 R2 Tag: 7zip
NanaZip Preview   M2Team.NanaZip.Preview 1.2.253.0          Tag: 7zip
NanaZip           M2Team.NanaZip         1.2.252.0          Tag: 7zip
7-Zip Alpha (msi) 7zip.7zip.Alpha.msi    21.03.00.0
7-Zip Alpha (exe) 7zip.7zip.Alpha.exe    21.04 beta

**Comment by accnetdev** [comment]
Microsoft Windows [version 10.0.19043.1766]

**Comment by Romanitho** [comment]
so wierd, it's works for me.
Does it work with the WiGui 1.6.3 or another ?

**Comment by accnetdev** [comment]
I tried, it does not work with 1.6.3 too.

**Comment by Romanitho** [comment]
no idea. Maybe different version of winget installed.

**Comment by Romanitho** [comment]
OK I think it's a Winget issue, that is fixed in their latest preview: 
https://github.com/microsoft/winget-cli/releases/tag/v1.3.1741

**Comment by accnetdev** [comment]
winget -v
v1.3.1611-preview

**Comment by accnetdev** [comment]
What is the MS approved method to update winget ?

**Comment by accnetdev** [comment]
winget -v
v1.3.1741
Just installed using msixbundle. Same issue.
I will try again after a reboot, but not sure that the update is the fix.

**Comment by Romanitho** [comment]
Strange. Have you tried on another computer ?

**Comment by accnetdev** [comment]
Yes, it works on several other PCs. But not on this one which is my main one under Microsoft Windows [version 10.0.19043.1806
![20220701_100500_PREDATORW10_eproust_capture](https://user-images.githubusercontent.com/32092909/176852553-51c62420-1398-44ec-b69c-f9d4fd1794ee.png)
]

**Comment by Romanitho** [comment]
strange. Do you run the WiGui "exe" or from cmd ?

**Comment by Romanitho** [comment]
ok.
Could you open a CMD as admin and run this:
`Powershell.exe Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Romanitho/Winget-Install-GUI/main/Sources/Winget-Install-GUI.ps1'))`

**Comment by accnetdev** [comment]
![20220701_101934_PREDATORW10_eproust_capture](https://user-images.githubusercontent.com/32092909/176854987-126ed45c-681f-4931-ba76-44106bebf778.png)

**Comment by accnetdev** [comment]
Winget search 7zip
Échec lors de la recherche de la source ; les résultats ne seront pas inclus : winget
Nom                               ID           Version Source
---------------------------------------------------------------
9 ZIP - open rar, zip, 7zip, gzip 9NBLGGH3TDHG Unknown msstore

**Comment by accnetdev** [comment]
There is an issue with the search of the source.

**Comment by Romanitho** [comment]
run a `winget source reset --force`

**Comment by accnetdev** [comment]
C:\WINDOWS\system32>winget source reset --force
Réinitialisation en cours de toutes les sources... Merci de patienter.Terminé

C:\WINDOWS\system32>winget source list
Nom     Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache

Still same error :-((

**Comment by Romanitho** [comment]
No worries. Appreciate your feedback ;)
But keep in mind that this project is based on Winget and reaches the Winget limits at this time. This project exists because we believe Winget to be the new reference in package management from MS and will be integrated naively in Intune soon.

**Comment by accnetdev** [comment]
Hi, Winget could became as good as apt in Linux Debian/Ubuntu but at this stage, it is not the case.
A command line/graphical package manager has to be reliable, unfortunately Microsoft has a big job to make Winget reliable because it has to manage a lot of external applications. 

We have to compare this to Apple macOS Drivers and Sofware and Microsoft Windows Drivers and Software : they are not on the same scope, the projet for Microsoft is huge and a lot easier for Apple.
