### ISSUE TITLE
Manage notifications

### ISSUE THREAD

**Issue by nononymousse** [Romanitho/Winget-Install-GUI#64]
Hi,
it would be nice to be able to manage notifications (like none, only the successful and failed updates, only the successful one, ect)

cuz i'm receiving too much but still want to see the ones that are (at least) successful

if others have ideas of how they could be manage/filtered too, feel free to comment

have a good day everyone ✨

**Comment by Romanitho** [comment]
Hi,

This kind of settings already exists

**Comment by nononymousse** [comment]
nevermind, i was thinking i could change this setting without reinstalling it

**Comment by Romanitho** [comment]
`-notificationlevel` settings

**Comment by Romanitho** [comment]
you can change it in the registry. Have a look on WAU documentation https://github.com/Romanitho/Winget-AutoUpdate
