### ISSUE TITLE
Make this app available on package managers

### ISSUE THREAD

**Issue by ppvnf** [Romanitho/Winget-Install-GUI#65]
Did you try adding this to Winget? And Chocolatey? I believe both require the binary to be signed. I am gonna make a request for adding to scoop if you don't mind.

**Comment by Romanitho** [comment]
never tried. but it's just a small gui from powershell ^^ and of course, not signed.

**Comment by ppvnf** [comment]
> never tried. but it's just a small gui from powershell ^^ and of course, not signed.

This was the reply for the issue I opened https://github.com/ScoopInstaller/Extras/issues/9475:

> This application does not meet the requirements for the extras bucket. We will have to wait for it to reach **at least 100 stars and 50 forks.**

**Comment by Romanitho** [comment]
haha, few more stars :)

**Comment by ppvnf** [comment]
https://github.com/ScoopInstaller/Extras/issues/9475#issuecomment-1283234789
