### ISSUE TITLE
The beginning and end of the names are cut off

### ISSUE THREAD

**Issue by Dhowti** [Romanitho/Winget-Install-GUI#67]
Hi! Win 11 22H2 Russian
![Screenshot](https://user-images.githubusercontent.com/108597329/198428724-aecb7103-f040-4877-b1c9-49fd601ed5eb.jpg)

**Comment by Romanitho** [comment]
we have issues with special caracters. This is due to Winget as it still doesn't offer proper powershell to work.
We can try to adapt code to better handle languages.
