### ISSUE TITLE
Error installing via PowerShell

### ISSUE THREAD

**Issue by sydbarrett74** [Romanitho/Winget-Install-GUI#68]
Hello,

I got the following error installing via PowerShell:

```
C:\Windows\System32>Powershell.exe Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Romanitho/Winget-Install-GUI/main/Sources/Winget-Install-GUI.ps1'))
No application found.
Exception setting "SelectedIndex": "InvalidArgument=Value of '0' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex"
At line:846 char:17
+                 $SubmitComboBox.SelectedIndex = 0
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
```

Please advise.

**Comment by Romanitho** [comment]
Hi,

It works for me. this is what I used, the same as yours:
`Powershell.exe Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Romanitho/Winget-Install-GUI/main/Sources/Winget-Install-GUI.ps1'))`

Have you tried cmd & powershell ?

**Comment by sydbarrett74** [comment]
I will report back with my findings. 😁

**Comment by sydbarrett74** [comment]
I was somehow able to put WinGet on my machine successfully. I can't recall specifically what I did (🙍‍♂️), so if I have future problems, I'll reopen this issue if it's relevant.
