### ISSUE TITLE
Make multiple choices in the result list possible (Shift/Ctrl marking)

### ISSUE THREAD

**Issue by Romanitho** [Romanitho/Winget-Install-GUI#7]
#3

**Comment by KnifMelti** [comment]
In the "**..matching Winget AppID**" scroll list too if it's not too much to ask for 🥇

**Comment by Romanitho** [comment]
the  **"..matching Winget AppID"**  is a droplist, not sure possible, and quite hard to implement regarding benefits 😅

**Comment by KnifMelti** [comment]
Then Remove in one go will do!
