### ISSUE TITLE
Option to run as User instead of only as Admin/System?

### ISSUE THREAD

**Issue by antgiant** [Romanitho/Winget-Install-GUI#73]
The precompiled exe forces itself to be run in the system/admin context. I would like to be able to use the GUI (and WAU in general) in the user context as well. Since winget fully supports both contexts are there any plans to allow this GUI to run in both contexts as well? It would be really nice to be able to use this GUI to manage both. Super amazing if it could coordinate WAU in both contexts so that all user and admin updates could be run from a single interface.

**Comment by Romanitho** [comment]
Hello. Free time is missing currently, but it's in the pipe to add new WAU features in WiGui :)

**Comment by Romanitho** [comment]
On latest version admin rights are not necessary anymore, but recommended to run with.
