### ISSUE TITLE
feature to export and import list with parameters

### ISSUE THREAD

**Issue by bandizsolt** [Romanitho/Winget-Install-GUI#82]
Hi!

When I install something I use the --interactive (-i) parameter with winget to show the install gui, to configure / view / supervise the installer. It is somehow possible to implement this option, to freely add / customize the install / uninstall commands parameters? Now you only can input the app id and thats it, from the script it is added automatically these parameters: --accept-source-agreements --accept-package-agreements -h.
I know that installing softs with these parameters will speed up the process, but what do you think about it?

Thank you!

**Comment by Romanitho** [comment]
Hi, thanks for your comment.
This tool is mainly used to install apps automatically with a list of apps for example. We could use a way to allow the fact that apps  install without the silent option.
Feel free to change the command in the script and try yourself to see if your setup can work, and we will think about the best way to implement your request :)
